serenity.project.name = BR_POC
webdriver.base.url = https://app.fi360test.com/app/security/login
webdriver.driver=chrome
webdriver.autodownload = true
#webdriver.chrome.driver = drivers/chromedriver.exe
webdriver.timeouts.implicitlywait = 10000
webdriver.wait.for.timeout = 15000
serenity.timeout = 30000
serenity.take.screenshots = AFTER_EACH_STEP
serenity.full.page.screenshot.strategy = true
chrome.switches = --disable-infobars
chrome.capabilities.acceptSslCerts = true
chrome.capabilities.handlesAlerts = true
serenity.console.colors = true
report.customfields.ApplicationVersion = 17.3.2.1
report.customfields.environment = QA
report.customfields.user = Praneetha Ramireddy
report.customfields.order=ApplicationVersion,environment,user
serenity.logging = NORMAL