serenity.project.name = BR_POC
webdriver.base.url = https://app.fi360test.com/app/security/login
webdriver.base.username =qzteam@test.com
webdriver.base.password =QZteam2025!
webdriver.driver=chrome
webdriver.autodownload = true
#webdriver.chrome.driver = drivers/chromedriver.exe
webdriver.timeouts.implicitlywait = 20000
webdriver.wait.for.timeout = 60000
serenity.timeout = 60000
webdriver.timeouts.pageLoadTimeout = 60000
serenity.take.screenshots = AFTER_EACH_STEP
serenity.full.page.screenshot.strategy = true
headless.mode = false
chrome.switches = --disable-infobars
chrome.capabilities.acceptSslCerts = true
chrome.capabilities.handlesAlerts = true
serenity.console.colors = true
report.customfields.ApplicationVersion = 17.3.2.1
report.customfields.environment = QA
report.customfields.user = Praneetha Ramireddy
report.customfields.order=ApplicationVersion,environment,user
serenity.logging = NORMAL